class cart_locator():
    cart_id = "cartur"
    order_button_xp = "//button[contains(text(),'Place Order')]"
    name_ID = "name"
    country_ID = "country"
    city_ID = "city"
    Creditcard_ID = "card"
    Month_ID = "month"
    Year_ID = "year"
    Purchase_XP = "//button[contains(text(),'Purchase')]"
    close_xp = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
    name_send_key = "Emanuel"
    country_send_key = "Isreal"
    city_send_key = "Beersheva"
    credit_send_key = "123456789101"
    month_send_key = "03"
    year_send_key = "2030"
    delete = "//a[contains(text(),'Delete')]"

